services:
  api:
    image: gijsvj/dev5:latest
    build: ./images/api
    ports:
      - 5000:3000
    environment: 
      PG_CONNECTION_STRING: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@store:5432/${POSTGRES_DB}"
    depends_on:
      store:
        condition: service_healthy
    command: ['npm','run','test']
  store:
    ports:
      - 5432:5432
    image: postgres:16.0
    environment: 
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
      POSTGRES_HOST_AUTH_METHOD: 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB "]
      interval: 5s
      timeout: 5s
      retries: 10

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30